site_name: Estudos de Machine Learning
site_url: https://guikingoak.github.io/Estudos_ML/

theme:
  name: material
  language: pt
  features:
    - navigation.instant   
    - toc.integrate        
    - code-copy           

nav:
  - Início: index.md
  - Atividade KNN: atvknn.md
  - Código KNN: atvknn.py
  - Dados: ytktk.csv

markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true  
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
