site_name: Estudos de Machine Learning
site_url: https://guikingoak.github.io/Estudos_ML/
repo_url: https://github.com/guikingoak/Estudos_ML
repo_name: guikingoak/Estudos_ML
theme:
  name: material
  palette:
    scheme: slate
    features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate

    markdown_extensions:
      - codehilite:
          guess_lang: false
      - admonition
      - toc:
          permalink: true
    
    nav:
      - Início: index.md
      - Atividade KNN: atvknn.md
      - Dados: ytktk.csv
      - Código: atvknn.py
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
